version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-NikiKalai@2003}
      MYSQL_DATABASE: ${DB_NAME:-greencart}
    ports:
      - "3307:3306"
    networks:
      - greencart_net
    volumes:
      - db_data:/var/lib/mysql

  etl:
    build: .
    container_name: greencart_etl
    depends_on:
      - mariadb
    environment:
      DB_HOST: ${DB_HOST:-mariadb}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-NikiKalai@2003}
      DB_NAME: ${DB_NAME:-greencart}
    networks:
      - greencart_net
    command: python3 src/pipeline.py
    volumes:
      - ./src:/app/src
      - ./data:/app/data

networks:
  greencart_net:
    driver: bridge

volumes:
  db_data:
